import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Topbar from '../components/Topbar';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Next Eth</title>
                <meta name="description" content="Generated by devcrazy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="rn-nft-mid-wrapper nft-left-sidebar-nav pr--40 pr_sm--15">
                <Topbar />
            </div>
        </div>
    );
};

export default Home;
